### ISSUE TITLE
Support quality percentage value for all formats where it's possible

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/php-image-converter#12]
>Perhaps we should have the quality validation before passing the `$quality` to specific `image` manipulation functions?

https://github.com/jenstornell/php-image-converter/issues/10#issuecomment-490398716

@peter279k 

The above gave me a new idea. Instead of having different types of quality ranges we could introduce a percentage value that works for every format that supports it.

**Current way**

This works now. Quality as integer.

```php
echo \ImageConverter\convert('image.gif', 'image.jpg', 70);
echo \ImageConverter\convert('image.jpg', 'image.png', 5);
```

**Additional way**

To not need to keep track of the different format quality range, it could support a unified percentage range (which will be converted to the correct value). To make it possible, check if it's a string.

```php
echo \ImageConverter\convert('image.gif', 'image.jpg', '70%');
echo \ImageConverter\convert('image.jpg', 'image.png', '60%');
```

Not yet sure if it's a good idea yet, but I'll throw it out here before I forget about it.

**Comment by peter279k** [comment]
I have the question about `Additional way`.

This way I don't suggest because it will make developers confused/difficult.

We have to add some descriptions about our `$quality` percentage in `README`.

Perhaps we have to calculate the current quality value before passing to related image functions.

I think we can follow the official function reference is for `$quality` definition in image functions.

It can help us to know `$quality` parameter easily.

And we only need to do is adding some image function references in `README`.

**Comment by jenstornell** [comment]
>Perhaps we have to calculate the current quality value before passing to related image functions.

You mean to throw an error if the quality value is not within the accepted range?

I agree with the rest.

**Comment by peter279k** [comment]
That's right.

Jens Törnell <notifications@github.com> 於 2019年5月8日 週三 下午7:24 寫道：

**Comment by jenstornell** [comment]
I agree that it may not be a good idea, but instead keep it to the PHP values and add it to the docs.
